### ISSUE TITLE
[FEAT] Implementation of Xception NN

### ISSUE THREAD

**Issue by EverLookNeverSee** [EverLookNeverSee/diag2model#19]
![Details](https://user-images.githubusercontent.com/57490926/138926665-9a0a9930-e22f-438a-9afa-df70dd73d13b.png)
![Xception_diagram](https://user-images.githubusercontent.com/57490926/138926706-7eb079ab-02e0-43c5-9e8e-81801aea6d39.png)

**Comment by prkhrsrvstv1** [comment]
Hi @EverLookNeverSee Requesting your review on #21
